### ISSUE TITLE
下载失败：ValueError("invalid padding byte")

### ISSUE THREAD

**Issue by iworldtong** [HorseCheng/Manga-Downloader#1]
下载时出现：
Traceback (most recent call last):
  File "t.py", line 159, in <module>
    downloader()
  File "t.py", line 34, in downloader
    decrypted += decrypter.feed()
  File "/Users/muketong/anaconda3/lib/python3.7/site-packages/pyaes/blockfeeder.py", line 169, in feed
    result = self._final(self._buffer, self._padding)
  File "/Users/muketong/anaconda3/lib/python3.7/site-packages/pyaes/blockfeeder.py", line 77, in _block_final_decrypt
    return strip_PKCS7_padding(self.decrypt(data))
  File "/Users/muketong/anaconda3/lib/python3.7/site-packages/pyaes/util.py", line 58, in strip_PKCS7_padding
    raise ValueError("invalid padding byte")
ValueError: invalid padding byte

**Comment by iworldtong** [comment]
已解决
